# Generated by Django 4.0.6 on 2022-07-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('room_id', 'date')},
        ),
    ]
