# Generated by Django 4.0.6 on 2022-07-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_roombooking_booking_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roombooking',
            unique_together=set(),
        ),
    ]
