# Generated by Django 4.0.6 on 2022-07-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_bookings_delete_roombooking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookings',
            unique_together={('room_id', 'booking_date')},
        ),
    ]
